resource "iosxe_errdisable" "errdisable" {
  for_each = { for device in local.devices : device.name => device if try(local.device_config[device.name].errdisable, null) != null || try(local.defaults.iosxe.configuration.errdisable, null) != null }
  device   = each.value.name

  detect_cause_all                              = try(local.device_config[each.value.name].errdisable.detect_cause.all, local.defaults.iosxe.configuration.errdisable.detect_cause.all, null)
  detect_cause_arp_inspection                   = try(local.device_config[each.value.name].errdisable.detect_cause.arp_insection, local.defaults.iosxe.configuration.errdisable.detect_cause.arp_insection, null)
  detect_cause_bpduguard                        = try(local.device_config[each.value.name].errdisable.detect_cause.bpduguard, local.defaults.iosxe.configuration.errdisable.detect_cause.bpduguard, null)
  detect_cause_dhcp_rate_limit                  = try(local.device_config[each.value.name].errdisable.detect_cause.dhcp_rate_limit, local.defaults.iosxe.configuration.errdisable.detect_cause.dhcp_rate_limit, null)
  detect_cause_dtp_flap                         = try(local.device_config[each.value.name].errdisable.detect_cause.dtp_flap, local.defaults.iosxe.configuration.errdisable.detect_cause.dtp_flap, null)
  detect_cause_gbic_invalid                     = try(local.device_config[each.value.name].errdisable.detect_cause.gbic_invalid, local.defaults.iosxe.configuration.errdisable.detect_cause.gbic_invalid, null)
  detect_cause_inline_power                     = try(local.device_config[each.value.name].errdisable.detect_cause.inline_power, local.defaults.iosxe.configuration.errdisable.detect_cause.inline_power, null)
  detect_cause_l2ptguard                        = try(local.device_config[each.value.name].errdisable.detect_cause.l2ptguard, local.defaults.iosxe.configuration.errdisable.detect_cause.l2ptguard, null)
  detect_cause_link_flap                        = try(local.device_config[each.value.name].errdisable.detect_cause.link_flap, local.defaults.iosxe.configuration.errdisable.detect_cause.link_flap, null)
  detect_cause_loopback                         = try(local.device_config[each.value.name].errdisable.detect_cause.loopback, local.defaults.iosxe.configuration.errdisable.detect_cause.loopback, null)
  detect_cause_loopdetect                       = try(local.device_config[each.value.name].errdisable.detect_cause.loopdetect, local.defaults.iosxe.configuration.errdisable.detect_cause.loopdetect, null)
  detect_cause_mlacp_minlink                    = try(local.device_config[each.value.name].errdisable.detect_cause.mlacp_minlink, local.defaults.iosxe.configuration.errdisable.detect_cause.mlacp_minlink, null)
  detect_cause_pagp_flap                        = try(local.device_config[each.value.name].errdisable.detect_cause.pagp_flap, local.defaults.iosxe.configuration.errdisable.detect_cause.pagp_flap, null)
  detect_cause_pppoe_ia_rate_limit              = try(local.device_config[each.value.name].errdisable.detect_cause.pppoe_ia_rate_limit, local.defaults.iosxe.configuration.errdisable.detect_cause.pppoe_ia_rate_limit, null)
  detect_cause_security_violation_shutdown_vlan = try(local.device_config[each.value.name].errdisable.detect_cause.security_violation_shutdown_vlan, local.defaults.iosxe.configuration.errdisable.detect_cause.security_violation_shutdown_vlan, null)
  detect_cause_sfp_config_mismatch              = try(local.device_config[each.value.name].errdisable.detect_cause.sfp_config_mismatch, local.defaults.iosxe.configuration.errdisable.detect_cause.sfp_config_mismatch, null)
  detect_cause_small_frame                      = try(local.device_config[each.value.name].errdisable.detect_cause.small_frame, local.defaults.iosxe.configuration.errdisable.detect_cause.small_frame, null)

  flap_setting_cause_dtp_flap_max_flaps  = try(local.device_config[each.value.name].errdisable.flap_setting_cause.dtp_flap_max_flaps, local.defaults.iosxe.configuration.errdisable.flap_setting_cause.dtp_flap_max_flaps, null)
  flap_setting_cause_dtp_flap_time       = try(local.device_config[each.value.name].errdisable.flap_setting_cause.dtp_flap_time, local.defaults.iosxe.configuration.errdisable.flap_setting_cause.dtp_flap_time, null)
  flap_setting_cause_link_flap_max_flaps = try(local.device_config[each.value.name].errdisable.flap_setting_cause.link_flap_max_flaps, local.defaults.iosxe.configuration.errdisable.flap_setting_cause.link_flap_max_flaps, null)
  flap_setting_cause_link_flap_time      = try(local.device_config[each.value.name].errdisable.flap_setting_cause.link_flap_time, local.defaults.iosxe.configuration.errdisable.flap_setting_cause.link_flap_time, null)
  flap_setting_cause_pagp_flap_max_flaps = try(local.device_config[each.value.name].errdisable.flap_setting_cause.pagp_flap_max_flaps, local.defaults.iosxe.configuration.errdisable.flap_setting_cause.pagp_flap_max_flaps, null)
  flap_setting_cause_pagp_flap_time      = try(local.device_config[each.value.name].errdisable.flap_setting_cause.pagp_flap_time, local.defaults.iosxe.configuration.errdisable.flap_setting_cause.pagp_flap_time, null)

  recovery_cause_all                  = try(local.device_config[each.value.name].errdisable.recovery_cause.all, local.defaults.iosxe.configuration.errdisable.recovery_cause.all, null)
  recovery_cause_arp_inspection       = try(local.device_config[each.value.name].errdisable.recovery_cause.arp_inspection, local.defaults.iosxe.configuration.errdisable.recovery_cause.arp_inspection, null)
  recovery_cause_bpduguard            = try(local.device_config[each.value.name].errdisable.recovery_cause.bpduguard, local.defaults.iosxe.configuration.errdisable.recovery_cause.bpduguard, null)
  recovery_cause_channel_misconfig    = try(local.device_config[each.value.name].errdisable.recovery_cause.channel_misconfig, local.defaults.iosxe.configuration.errdisable.recovery_cause.channel_misconfig, null)
  recovery_cause_dhcp_rate_limit      = try(local.device_config[each.value.name].errdisable.recovery_cause.dhcp_rate_limit, local.defaults.iosxe.configuration.errdisable.recovery_cause.dhcp_rate_limit, null)
  recovery_cause_dtp_flap             = try(local.device_config[each.value.name].errdisable.recovery_cause.dtp_flap, local.defaults.iosxe.configuration.errdisable.recovery_cause.dtp_flap, null)
  recovery_cause_gbic_invalid         = try(local.device_config[each.value.name].errdisable.recovery_cause.gbic_invalid, local.defaults.iosxe.configuration.errdisable.recovery_cause.gbic_invalid, null)
  recovery_cause_inline_power         = try(local.device_config[each.value.name].errdisable.recovery_cause.inline_power, local.defaults.iosxe.configuration.errdisable.recovery_cause.inline_power, null)
  recovery_cause_l2ptguard            = try(local.device_config[each.value.name].errdisable.recovery_cause.l2ptguard, local.defaults.iosxe.configuration.errdisable.recovery_cause.l2ptguard, null)
  recovery_cause_link_flap            = try(local.device_config[each.value.name].errdisable.recovery_cause.link_flap, local.defaults.iosxe.configuration.errdisable.recovery_cause.link_flap, null)
  recovery_cause_link_monitor_failure = try(local.device_config[each.value.name].errdisable.recovery_cause.link_monitor_failure, local.defaults.iosxe.configuration.errdisable.recovery_cause.link_monitor_failure, null)
  recovery_cause_loopback             = try(local.device_config[each.value.name].errdisable.recovery_cause.loopback, local.defaults.iosxe.configuration.errdisable.recovery_cause.loopback, null)
  recovery_cause_mac_limit            = try(local.device_config[each.value.name].errdisable.recovery_cause.mac_limit, local.defaults.iosxe.configuration.errdisable.recovery_cause.mac_limit, null)
  recovery_cause_mlacp_minlink        = try(local.device_config[each.value.name].errdisable.recovery_cause.mlacp_minlink, local.defaults.iosxe.configuration.errdisable.recovery_cause.mlacp_minlink, null)
  recovery_cause_pagp_flap            = try(local.device_config[each.value.name].errdisable.recovery_cause.pagp_flap, local.defaults.iosxe.configuration.errdisable.recovery_cause.pagp_flap, null)
  recovery_cause_port_mode_failure    = try(local.device_config[each.value.name].errdisable.recovery_cause.port_mode_failure, local.defaults.iosxe.configuration.errdisable.recovery_cause.port_mode_failure, null)
  recovery_cause_pppoe_ia_rate_limit  = try(local.device_config[each.value.name].errdisable.recovery_cause.pppoe_ia_rate_limit, local.defaults.iosxe.configuration.errdisable.recovery_cause.pppoe_ia_rate_limit, null)
  recovery_cause_psp                  = try(local.device_config[each.value.name].errdisable.recovery_cause.psp, local.defaults.iosxe.configuration.errdisable.recovery_cause.psp, null)
  recovery_cause_psecure_violation    = try(local.device_config[each.value.name].errdisable.recovery_cause.psecure_violation, local.defaults.iosxe.configuration.errdisable.recovery_cause.psecure_violation, null)
  recovery_cause_security_violation   = try(local.device_config[each.value.name].errdisable.recovery_cause.security_violation, local.defaults.iosxe.configuration.errdisable.recovery_cause.security_violation, null)
  recovery_cause_sfp_config_mismatch  = try(local.device_config[each.value.name].errdisable.recovery_cause.sfp_config_mismatch, local.defaults.iosxe.configuration.errdisable.recovery_cause.sfp_config_mismatch, null)
  recovery_cause_small_frame          = try(local.device_config[each.value.name].errdisable.recovery_cause.small_frame, local.defaults.iosxe.configuration.errdisable.recovery_cause.small_frame, null)
  recovery_cause_storm_control        = try(local.device_config[each.value.name].errdisable.recovery_cause.storm_control, local.defaults.iosxe.configuration.errdisable.recovery_cause.storm_control, null)
  recovery_cause_udld                 = try(local.device_config[each.value.name].errdisable.recovery_cause.udld, local.defaults.iosxe.configuration.errdisable.recovery_cause.udld, null)
  recovery_cause_unicast_flood        = try(local.device_config[each.value.name].errdisable.recovery_cause.unicast_flood, local.defaults.iosxe.configuration.errdisable.recovery_cause.unicast_flood, null)
  recovery_cause_vmps                 = try(local.device_config[each.value.name].errdisable.recovery_cause.vmps, local.defaults.iosxe.configuration.errdisable.recovery_cause.vmps, null)
  recovery_cause_loopdetect           = try(local.device_config[each.value.name].errdisable.recovery_cause.loopdetect, local.defaults.iosxe.configuration.errdisable.recovery_cause.loopdetect, null)
}